import fetch from 'node-fetch';
import { AIProvider, ChatMessage, ModelInfo, ToolDefinition, ToolCall } from './base';
export class OpenAICompatProvider extends AIProvider {
  constructor(private baseUrl:string, private apiKey:string, private name:string){ super(); }
  private url(p:string){ return this.baseUrl.replace(/\/$/,'')+p; }
  private headers():any{ return {'Content-Type':'application/json','Authorization':`Bearer ${this.apiKey}`}; }
  async testConnection(){ try{ if(!this.apiKey) return {ok:false,error:'No API key'}; const r=await fetch(this.url('/models'),{headers:this.headers()}); return r.ok?{ok:true}:{ok:false,error:`${r.status}`}; }catch(e:any){ return {ok:false,error:e.message}; } }
  async getModels():Promise<ModelInfo[]>{ const r=await fetch(this.url('/models'),{headers:this.headers()}); if(!r.ok) throw new Error(`${r.status}`); const j:any=await r.json(); return j.data||[]; }
  async chatCompletion(opts:{model:string;messages:ChatMessage[];tools?:ToolDefinition[]}):Promise<string>{ const b:any={model:opts.model,messages:opts.messages,temperature:0.2}; if(opts.tools?.length) b.tools=opts.tools; const r=await fetch(this.url('/chat/completions'),{method:'POST',headers:this.headers(),body:JSON.stringify(b)}); if(!r.ok) throw new Error(await r.text()); const j:any=await r.json(); return j.choices?.[0]?.message?.content||''; }
  async streamChat(opts:{model:string;messages:ChatMessage[];tools?:ToolDefinition[];temperature?:number;max_tokens?:number;onToken:(t:string)=>void;onToolCall?:(tc:ToolCall[])=>void;onDone:()=>void;onError:(e:string)=>void}):Promise<void>{
    const body:any={model:opts.model,messages:opts.messages,temperature:opts.temperature??0.2,max_tokens:opts.max_tokens,stream:true}; if(opts.tools?.length){body.tools=opts.tools; body.tool_choice='auto';}
    try{ const r:any=await fetch(this.url('/chat/completions'),{method:'POST',headers:this.headers(),body:JSON.stringify(body)}); if(!r.ok){ opts.onError(await r.text()); return; } let buf=''; const map=new Map<number,any>(); for await(const c of r.body){ const s=c.toString(); buf+=s; const lines=buf.split('\n'); buf=lines.pop()||''; for(const line of lines){ const t=line.trim(); if(!t||t==='data: [DONE]') continue; if(!t.startsWith('data: ')) continue; const d=t.slice(6); if(d==='[DONE]'){ opts.onDone(); return; } try{ const j=JSON.parse(d); const delta=j.choices?.[0]?.delta; if(delta?.content) opts.onToken(delta.content); if(delta?.tool_calls){ for(const tc of delta.tool_calls){ const idx=tc.index??0; if(!map.has(idx)) map.set(idx,{id:tc.id||`call_${idx}`,type:'function',function:{name:tc.function?.name||'',arguments:tc.function?.arguments||''}}); else{ const cur=map.get(idx); if(tc.function?.name) cur.function.name=tc.function.name; if(tc.function?.arguments) cur.function.arguments+=tc.function.arguments; } } } if(j.choices?.[0]?.finish_reason==='tool_calls'){ const calls=[...map.values()]; if(calls.length&&opts.onToolCall) opts.onToolCall(calls); map.clear(); } }catch{} } } if(map.size&&opts.onToolCall) opts.onToolCall([...map.values()]); opts.onDone(); }catch(e:any){ opts.onError(e.message); }
  }
  updateConfig(baseUrl:string, apiKey:string){ if(baseUrl) this.baseUrl=baseUrl; if(apiKey) this.apiKey=apiKey; }
}